"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { deleteConsultingImageAction, generateConsultingAuditAction, moveConsultingStageAction, promoteConsultingLeadAction, saveConsultingWorkspaceAction, setCommercialTrackAction, uploadConsultingImagesAction } from "../../app/actions/consulting.js";
import { CONSULTING_STAGES, CONSULTING_STATUS_LABELS } from "../../services/consulting/stages.js";
import { COMMERCIAL_TRACKS } from "../../services/leads/commercialTrack.js";
import s from "./ConsultingWorkspace.module.css";

function parseAudit(value) { if (!value) return null; try { return typeof value === "string" ? JSON.parse(value) : value; } catch { return null; } }
function money(cents) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(cents || 0) / 100); }
function dateTime(value) { if (!value) return "Ainda não realizado"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "Ainda não realizado" : date.toLocaleString("pt-BR"); }
function whatsappLink(lead, message) { let digits = String(lead.whatsapp || lead.phone || "").replace(/\D/g, ""); if (!digits) return ""; if (!digits.startsWith("55")) digits = `55${digits}`; return `https://wa.me/${digits}${message ? `?text=${encodeURIComponent(message)}` : ""}`; }
const CATEGORY_LABELS = { seo: "SEO técnico", conversion: "Conversão", mobile: "Experiência mobile", trust: "Confiança", local: "Presença local" };

export default function ConsultingWorkspace({ initialLead, initialWorkspace, initialProfile = {}, initialAssets = [] }) {
  const router = useRouter(), initial = initialWorkspace.consulting || {};
  const [consulting, setConsulting] = useState(initial), [commercialTrack, setCommercialTrack] = useState(initialWorkspace.commercialTrack || "consulting"), [assets, setAssets] = useState(initialAssets), [websiteUrl, setWebsiteUrl] = useState(initial.websiteUrl || initialLead.site || ""), [instagramUrl, setInstagramUrl] = useState(initial.instagramUrl || initialLead.instagram || ""), [instagramNotes, setInstagramNotes] = useState(initial.instagramNotes || ""), [report, setReport] = useState(initial.report || ""), [whatsappMessage, setWhatsappMessage] = useState(initial.whatsappMessage || ""), [priceCents, setPriceCents] = useState(Number(initial.priceCents || 5000)), [busy, setBusy] = useState(""), [notice, setNotice] = useState(""), [noticeKind, setNoticeKind] = useState("success");
  const audit = useMemo(() => parseAudit(consulting.auditSnapshot), [consulting.auditSnapshot]), wa = useMemo(() => whatsappLink(initialLead, whatsappMessage), [initialLead, whatsappMessage]), categories = audit?.categoryScores || {};
  function showNotice(message, kind = "success") { setNoticeKind(kind); setNotice(message); }
  async function savePatch(patch, success = "Alterações salvas.") {
    const before = consulting;
    setConsulting(current => ({ ...current, ...patch }));
    try { const saved = await saveConsultingWorkspaceAction(initialLead.id, patch); setConsulting(saved); showNotice(success); router.refresh(); return saved; }
    catch (error) { setConsulting(before); showNotice(`Erro: ${error.message}`, "error"); return null; }
  }
  async function saveSources() { setBusy("sources"); setNotice(""); await savePatch({ websiteUrl, instagramUrl, instagramNotes, priceCents }, "Dados e observações salvos."); setBusy(""); }
  async function changeCommercialTrack(value) {
    setBusy("track"); setNotice("");
    try { const saved = await setCommercialTrackAction(initialLead.id, value); setCommercialTrack(saved.commercialTrack); showNotice("Tipo de oportunidade atualizado sem alterar a nota do lead."); router.refresh(); }
    catch (error) { showNotice(`Erro: ${error.message}`, "error"); }
    finally { setBusy(""); }
  }
  async function uploadImages(event) {
    const files = Array.from(event.target.files || []); event.target.value = ""; if (!files.length) return;
    setBusy("upload"); setNotice("");
    try { const formData = new FormData(); formData.set("leadId", initialLead.id); files.forEach(file => formData.append("images", file)); setAssets(await uploadConsultingImagesAction(formData)); setCommercialTrack(current => current === "both" ? "both" : "consulting"); showNotice(`${files.length} imagem${files.length === 1 ? "" : "s"} adicionada${files.length === 1 ? "" : "s"} para a análise visual.`); router.refresh(); }
    catch (error) { showNotice(`Erro no upload: ${error.message}`, "error"); }
    finally { setBusy(""); }
  }
  async function removeImage(asset) {
    if (!window.confirm(`Remover "${asset.label}" da análise?`)) return;
    setBusy(`delete-${asset.id}`);
    try { setAssets(await deleteConsultingImageAction(initialLead.id, asset.id)); showNotice("Imagem removida."); }
    catch (error) { showNotice(`Erro: ${error.message}`, "error"); }
    finally { setBusy(""); }
  }
  async function generateAudit() {
    if (!websiteUrl.trim() && !instagramUrl.trim() && !instagramNotes.trim() && !assets.length) { showNotice("Informe o site, o Instagram, observações ou envie imagens antes de analisar.", "error"); return; }
    setBusy("audit"); setNotice("");
    try {
      const result = await generateConsultingAuditAction({ leadId: initialLead.id, websiteUrl, instagramUrl, instagramNotes, priceCents });
      const patch = { stage: "diagnostico", status: "ready", websiteUrl, instagramUrl, instagramNotes, auditSnapshot: JSON.stringify(result.websiteAudit || null), overallScore: Number(result.overallScore || 0), executiveSummary: result.executiveSummary || "", visualSummary: result.visualSummary || "", report: result.report || "", whatsappMessage: result.whatsappMessage || "", priceCents, lastAnalyzedAt: new Date().toISOString(), diagnosisProviderName: result.diagnosis?.providerName || "", diagnosisModel: result.diagnosis?.model || "", reportProviderName: result.reportGeneration?.providerName || "", reportModel: result.reportGeneration?.model || "", diagnosisAiUsed: Boolean(result.diagnosis?.aiUsed), reportAiUsed: Boolean(result.reportGeneration?.aiUsed), warning: result.warning || "" };
      const saved = await saveConsultingWorkspaceAction(initialLead.id, patch);
      setConsulting(saved); setReport(saved.report || ""); setWhatsappMessage(saved.whatsappMessage || ""); setAssets(result.assets || assets); setCommercialTrack(current => current === "both" ? "both" : "consulting"); showNotice("Diagnóstico, abordagem e relatório foram processados em duas etapas."); router.refresh();
    } catch (error) { showNotice(`Erro ao gerar análise: ${error.message}`, "error"); }
    finally { setBusy(""); }
  }
  async function saveContent() { setBusy("content"); await savePatch({ report, whatsappMessage, status: "reviewed", priceCents }, "Relatório e mensagem revisados."); setBusy(""); }
  async function changeStage(stage) { setBusy("stage"); setNotice(""); try { const saved = await moveConsultingStageAction(initialLead.id, stage, stage === "perdido" ? "lost" : ""); setConsulting(saved); showNotice("Etapa atualizada."); router.refresh(); } catch (error) { showNotice(`Erro: ${error.message}`, "error"); } finally { setBusy(""); } }
  async function changeStatus(status) {
    const stage = status === "sent" ? "contatado" : ["interested", "payment_pending"].includes(status) ? "negociacao" : ["paid", "delivered", "converted"].includes(status) ? "cliente" : status === "lost" ? "perdido" : consulting.stage;
    await savePatch({ status, stage }, "Substatus atualizado.");
  }
  async function markPaid() { setBusy("payment"); await savePatch({ paymentStatus: "paid", status: "paid", stage: "cliente", soldAt: consulting.soldAt || new Date().toISOString(), priceCents }, "Pagamento confirmado e consultoria marcada como cliente."); setBusy(""); }
  async function markDelivered() { setBusy("delivery"); await savePatch({ status: "delivered", stage: "cliente", deliveredAt: new Date().toISOString() }, "Consultoria marcada como entregue."); setBusy(""); }
  async function promoteToProject() {
    if (!window.confirm("Adicionar este cliente também ao CRM de projetos? A nota atual será preservada.")) return;
    setBusy("promote"); setNotice("");
    try { await promoteConsultingLeadAction(initialLead.id); setCommercialTrack("both"); router.push(`/crm/${initialLead.id}`); router.refresh(); }
    catch (error) { showNotice(`Erro ao converter oportunidade: ${error.message}`, "error"); setBusy(""); }
  }
  async function openWhatsapp() { await savePatch({ status: "sent", stage: "contatado", lastContactAt: new Date().toISOString() }, "Abordagem marcada como enviada."); }
  async function copy(value, message) { try { await navigator.clipboard.writeText(value || ""); showNotice(message); } catch { showNotice("Não foi possível copiar automaticamente.", "error"); } }

  return <main className={s.page}>
    <header className={`${s.header} ${s.noPrint}`}><div><a href="/consultoria">← Voltar para consultorias</a><span>Consultoria Express</span><h1>{initialLead.name}</h1><p>{initialLead.segment || "Sem categoria"} · {[initialLead.city, initialLead.location].filter(Boolean).join(", ") || "Local não informado"} · Nota {initialLead.grade}</p></div><div className={s.headerScore}><strong>{consulting.overallScore || "—"}</strong><span>score digital</span></div></header>
    {notice && <div className={`${s.notice} ${noticeKind === "error" ? s.noticeError : ""} ${s.noPrint}`}>{notice}</div>}{consulting.warning && <div className={`${s.warning} ${s.noPrint}`}>{consulting.warning}</div>}
    <section className={`${s.trackCard} ${s.noPrint}`}><div><span>Tipo de oportunidade</span><strong>Independente da nota {initialLead.grade}</strong><small>Escolha em quais CRMs este lead deve aparecer.</small></div><select value={commercialTrack} disabled={busy === "track"} onChange={event => changeCommercialTrack(event.target.value)}>{COMMERCIAL_TRACKS.filter(item => item.id !== "auto").map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></section>
    <section className={`${s.stageBar} ${s.noPrint}`}>{CONSULTING_STAGES.map(stage => <button key={stage.id} type="button" className={consulting.stage === stage.id ? s.stageActive : ""} disabled={busy === "stage"} onClick={() => changeStage(stage.id)}>{stage.label}</button>)}</section>
    <section className={`${s.grid} ${s.noPrint}`}>
      <div className={s.card}><div className={s.cardHead}><div><span>Etapa 1</span><h2>Fontes e evidências</h2></div><button type="button" disabled={busy === "sources"} onClick={saveSources}>{busy === "sources" ? "Salvando..." : "Salvar dados"}</button></div><label><span>Site existente</span><input value={websiteUrl} onChange={event => setWebsiteUrl(event.target.value)} placeholder="https://empresa.com.br" /></label><label><span>Instagram</span><input value={instagramUrl} onChange={event => setInstagramUrl(event.target.value)} placeholder="https://instagram.com/empresa" /></label><label><span>Observações ou dados do Instagram</span><textarea value={instagramNotes} onChange={event => setInstagramNotes(event.target.value)} placeholder="Cole a bio, descreva destaques, frequência, identidade visual e informações observadas. Você também pode enviar prints abaixo." /></label><div className={s.uploadBox}><div><strong>Enviar prints do Instagram</strong><span>PNG, JPG ou WebP, até 5 MB por imagem.</span></div><label className={s.uploadButton}><input type="file" accept="image/png,image/jpeg,image/webp" multiple disabled={busy === "upload"} onChange={uploadImages} />{busy === "upload" ? "Enviando..." : "Selecionar imagens"}</label></div><label><span>Preço da Consultoria Express</span><input type="number" min="0" step="0.01" value={priceCents / 100} onChange={event => setPriceCents(Math.max(0, Math.round(Number(event.target.value || 0) * 100)))} /></label><button className={s.primary} type="button" disabled={busy === "audit"} onClick={generateAudit}>{busy === "audit" ? "Capturando e analisando..." : "Gerar diagnóstico completo"}</button><small>O LeadFlow tentará gerar capturas desktop e mobile automaticamente. Depois fará uma chamada curta para diagnóstico e outra separada para o relatório.</small></div>
      <div className={s.card}><div className={s.cardHead}><div><span>Evidências visuais</span><h2>Capturas e prints enviados</h2></div></div>{assets.length ? <div className={s.gallery}>{assets.map(asset => <figure key={asset.id}><a href={asset.url} target="_blank" rel="noopener noreferrer"><img src={asset.url} alt={asset.label} /></a><figcaption><span>{asset.label}</span><button type="button" disabled={busy === `delete-${asset.id}`} onClick={() => removeImage(asset)}>Remover</button></figcaption></figure>)}</div> : <div className={s.empty}>As capturas automáticas e os prints enviados aparecerão aqui.</div>}</div>
    </section>
    <section className={`${s.card} ${s.noPrint}`}><div className={s.cardHead}><div><span>Diagnóstico técnico</span><h2>Score por área</h2></div><span className={s.statusPill}>{CONSULTING_STATUS_LABELS[consulting.status] || "Pendente"}</span></div>{audit?.error ? <div className={s.auditError}>{audit.error}</div> : audit ? <><div className={s.categoryGrid}>{Object.entries(CATEGORY_LABELS).map(([key, label]) => <div key={key}><strong>{categories[key] ?? "—"}</strong><span>{label}</span></div>)}</div><div className={s.metrics}><div><strong>{audit.responseTimeMs ? `${audit.responseTimeMs}ms` : "—"}</strong><span>resposta</span></div><div><strong>{audit.h1Count ?? "—"}</strong><span>H1</span></div><div><strong>{audit.formCount ?? "—"}</strong><span>formulários</span></div><div><strong>{audit.hasWhatsapp ? "Sim" : "Não"}</strong><span>WhatsApp</span></div></div><div className={s.factList}><p><strong>Título:</strong> {audit.title || "Não encontrado"}</p><p><strong>Descrição:</strong> {audit.metaDescription || "Não encontrada"}</p><p><strong>Privacidade:</strong> {audit.hasPrivacyLink ? "Encontrada" : "Não encontrada"}</p><p><strong>Mapa/endereço:</strong> {audit.hasMapsLink || audit.hasAddress ? "Identificado" : "Não identificado"}</p></div><div className={s.findings}><div><h3>Pontos positivos</h3>{(audit.positives || []).map(item => <p key={item}>✓ {item}</p>)}</div><div><h3>Oportunidades</h3>{(audit.issues || []).map(item => <p key={item}>• {item}</p>)}</div></div></> : <div className={s.empty}>O diagnóstico técnico aparecerá aqui.</div>}{consulting.visualSummary && <div className={s.visualSummary}><h3>Análise visual da IA</h3><p>{consulting.visualSummary}</p></div>}<dl className={s.meta}><div><dt>Última análise</dt><dd>{dateTime(consulting.lastAnalyzedAt)}</dd></div><div><dt>Diagnóstico</dt><dd>{consulting.diagnosisAiUsed ? `${consulting.diagnosisProviderName} · ${consulting.diagnosisModel}` : "Fallback técnico"}</dd></div><div><dt>Relatório</dt><dd>{consulting.reportAiUsed ? `${consulting.reportProviderName} · ${consulting.reportModel}` : "Fallback local"}</dd></div></dl></section>
    <section className={`${s.editorGrid} ${s.noPrint}`}><div className={s.card}><div className={s.cardHead}><div><span>Etapa 2</span><h2>Relatório completo</h2></div><button type="button" onClick={() => copy(report, "Relatório copiado.")}>Copiar</button></div><textarea className={s.reportEditor} value={report} onChange={event => setReport(event.target.value)} placeholder="O relatório completo será gerado aqui." /></div><div className={s.card}><div className={s.cardHead}><div><span>Etapa 3</span><h2>Abordagem por WhatsApp</h2></div><button type="button" onClick={() => copy(whatsappMessage, "Mensagem copiada.")}>Copiar</button></div><textarea className={s.messageEditor} value={whatsappMessage} onChange={event => setWhatsappMessage(event.target.value)} placeholder="A mensagem de abordagem será gerada aqui." /><div className={s.actions}><button type="button" disabled={busy === "content"} onClick={saveContent}>{busy === "content" ? "Salvando..." : "Salvar revisão"}</button>{wa ? <a className={s.whatsapp} href={wa} target="_blank" rel="noopener noreferrer" onClick={openWhatsapp}>Abrir WhatsApp</a> : <span>Lead sem WhatsApp válido</span>}</div></div></section>
    <section className={`${s.commercial} ${s.noPrint}`}><div><span>Oferta atual</span><strong>{money(priceCents)}</strong><small>Consultoria Express</small></div><div><span>Pagamento</span><strong>{consulting.paymentStatus === "paid" ? "Pago" : "Pendente"}</strong><small>Venda: {dateTime(consulting.soldAt)}</small></div><div><span>Entrega</span><strong>{consulting.status === "delivered" ? "Entregue" : "Pendente"}</strong><small>{dateTime(consulting.deliveredAt)}</small></div><label className={s.statusSelect}><span>Substatus</span><select value={consulting.status || "pending"} onChange={event => changeStatus(event.target.value)}>{Object.entries(CONSULTING_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className={s.commercialActions}><button type="button" onClick={() => changeStatus("interested")}>Marcar interessado</button><button type="button" onClick={() => changeStatus("payment_pending")}>Aguardando pagamento</button><button type="button" disabled={busy === "payment"} onClick={markPaid}>Confirmar pagamento</button><button type="button" disabled={!report || busy === "delivery"} onClick={markDelivered}>Marcar como entregue</button><button type="button" disabled={!report} onClick={() => window.print()}>Imprimir / salvar PDF</button><button className={s.promote} type="button" disabled={busy === "promote"} onClick={promoteToProject}>{busy === "promote" ? "Convertendo..." : "Adicionar ao CRM de projetos"}</button></div></section>
    <article className={s.printReport}><header><span>CONSULTORIA EXPRESS DE PRESENÇA DIGITAL</span><h1>{initialLead.name}</h1><p>{initialLead.segment || "Empresa"} · {[initialLead.city, initialLead.location].filter(Boolean).join(", ")}</p></header><div className={s.printScore}><strong>{consulting.overallScore || "—"}</strong><span>Diagnóstico geral</span></div><pre>{report || "O relatório ainda não foi gerado."}</pre><footer><strong>{initialProfile.name || initialProfile.brandName || "LeadFlow"}</strong><span>{initialProfile.profession || "Consultoria de presença digital"}</span></footer></article>
  </main>;
}
